### PR TITLE
Settings links initial feedback link

### PR DESCRIPTION
**Pull request by natlibfi-max-grasbeck**
Adds a hardcoded feedback form in a webview. Softcoding will be looked into after release.

### CODE REVIEW

**Review by NatLibFi-JoonaKupe — APPROVED** [review]
We seem to have a reason to look into linking for future purposes. Potential go-around solution that is currently forking, if no other solution available until launch, we'll go with this one.

**Review by NatLibFi-JoonaKupe — CHANGES_REQUESTED** [review]
Potential go-around solution that is currently forking, if no other solution available until launch, we'll go with this one.

**Comment by natlibfi-max-grasbeck** [comment]
There is a simpler way to do this that involves translations that we'll be using instead of this.

**Comment by mikko-work** [comment]
I would go with this solution as well. Modifications are in many places, but they are quite clear and should be easy to handle in a possible merge with upstream. I would not do any "hacky" solutions since those may cause side-effects in the long run, as they work against intended application logic.

**Comment by natlibfi-max-grasbeck** [comment]
We will be reverting to this solution in a properly named branch.

**Pull request closed without merging**
