### PR TITLE
Fix remove button location

### PR DESCRIPTION
**Pull request by natlibfi-burger**
Removed the code that dealt with
previewButton in the onBookStatusHeld part 
of the CatalogButtons, and removed some
spaces that made the button layout
inconsistent with other button layouts.

Ref SIMPLYE-386

### CODE REVIEW

**Comment by natlibfi-burger** [comment]
No, this removes the creation of the preview button completely,.

**Comment by sylvain-degeilh-lingsoft** [comment]
We need to keep the preview button. Just that if no preview is available, then it should not occupy the space.

**Comment by kankaristo** [comment]
The Palace Android app has some really weird code in some places... Normally this would just be changing the button's visibility between `View.GONE` and `View.VISIBLE` (or `View.INVISIBLE`, if you want it to take up space but be hidden), now they're creating a "button sized space"...?

**Comment by natlibfi-burger** [comment]
Yes, but that button sized space is also used to "pad out" the end of the button container in the case that there is only one button. Otherwise the button would be the width of the button container. They seem to want to keep the buttons always in the same spots, which is different from our application.

**Comment by sylvain-degeilh-lingsoft** [comment]
In this case, if it's too complicated, then we just leave the button in place. We want to keep the preview button functionality.

**Comment by natlibfi-burger** [comment]
Added back the preview button, and the spacing should be correct now if there is no preview button.

**Review by sylvain-degeilh-lingsoft — APPROVED** [review]

**Pull request merged**
